### ISSUE TITLE
段落能首行缩进2字符吗？

### ISSUE THREAD

**Issue by ybbluesky** [mefengl/WeRead-Helper#3]
段落能首行缩进2字符吗？能帮助实现吗？

**Comment by mefengl** [comment]
> 首行缩进的目的如果是区分段落，那么段落之间的段间距已经做到了，不会考虑做这个功能。  
>   
> 另外，真要实现的话，微信读书做了很多防Copy的工作，很多时候网页上不是p或div，而是canvas，简单来说，很难  

https://greasyfork.org/zh-CN/scripts/420774-微信读书阅读助手/discussions/143605
