### ISSUE TITLE
页面不断刷新

### ISSUE THREAD

**Issue by NNGTHB** [mefengl/WeRead-Helper#4]
![动画](https://user-images.githubusercontent.com/115760745/217775656-da7daa12-e1e0-4979-9015-21b154042ce3.gif)

在关闭和微信读书有关的谷歌插件和其他脚本后，开启此脚本页面会不停地刷新，请问如何解决呢？

**Comment by mefengl** [comment]
![image](https://user-images.githubusercontent.com/71683364/217779042-c3bdd11f-f62b-42e3-b16c-85c01d894e3d.png)
@NNGTHB 你试试看把这个数字改成5000

可能的确是500毫秒的加载时间给少了

**Comment by NNGTHB** [comment]
> ![image](https://user-images.githubusercontent.com/71683364/217779042-c3bdd11f-f62b-42e3-b16c-85c01d894e3d.png) @NNGTHB 你试试看把这个数字改成 5000
> 
> 可能的确是 500 毫秒的加载时间给少了

谢谢完美解决了

**Comment by mefengl** [comment]
已在新版本中延长时间到2500毫秒，https://github.com/mefengl/wereadhelper/commit/8ba8e592469e10a4a077603257ee76bd11a7f3e5
