### ISSUE TITLE
宽屏的处理

### ISSUE THREAD

**Issue by samonysh** [mefengl/WeRead-Helper#6]
用脚本的时候如果页面比较窄的话，会出现.app_content宽度在1000px，而顶栏宽度只有700px左右的情况，造成顶栏与阅读页面没对齐的情况。同时，侧边栏会遮挡阅读页面。这两个问题都影响了阅读体验。
我自己调了一下，用百分比可能会更好一些，代码如下：
`
 // 功能1️⃣：宽屏
  $(function () {
    $(".app_content").css("maxWidth", "75%");
    $(".readerTopBar").css("maxWidth", "75%");
    $(".readerControls").css("margin-left","0px");
    $(".readerControls").css("left","90%");
    // $(".readerTopBar").css("display", "flex");
  });
`

**Comment by mefengl** [comment]
非常感谢您的反馈！测试了修改前和修改后的代码情况如下:

这个问题我之前好像也遇到过，但是刚才尝试了几次都没有再次出现。可能是因为不同的操作系统和浏览器版本导致的差异，同时也可能与是否安装了其他微信读书脚本有关。

这是现在的代码可以达到的最窄的情况：

<img width="450" alt="image" src="https://user-images.githubusercontent.com/71683364/230783714-c2e9c48c-5cb7-4065-97d6-be3412c6f0e1.png">


也试了你提供的代码，本地测试最窄如下：

<img width="211" alt="image" src="https://user-images.githubusercontent.com/71683364/230783966-e247d3ee-4c0e-41cc-a893-8460bcc50f4a.png">

然后普通情况如下：

<img width="1171" alt="image" src="https://user-images.githubusercontent.com/71683364/230784012-f86ceaea-247a-44e0-af65-b54964dadcc6.png">

总结下来，可能是现有的代码与你的配置不兼容，而提供的修改代码则在我的配置下也无法正常运行。

你可以 fork 这个仓库来保留你的配置，同时也能同步获取最新的更改

**Comment by samonysh** [comment]
谢谢您的回应
我的电脑是windows+vivaldi。
因为我电脑的屏幕是2k的，而脚本最大支持的是1000px，有时候有点嫌小就会修改一下。
理论上flex应该有平齐的效果，但是不知道为啥在我的电脑上就是没体现那个效果。对于普通情况下新出现的问题，我也不太清楚是怎么回事，有可能是在点了“简化书城页面的时候”又重新复写了有关顶栏的css。

我也觉得应该是跟我的配置不太兼容。
我之后会fork这个仓库来保存我的修改。

十分感谢您提供的插件优化了微信读书的阅读体验。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月10日 00:27 |
| 收件人 | ***@***.***> |
| 抄送至 | Samon ***@***.***>***@***.***> |
| 主题 | Re: [mefengl/wereadhelper] 宽屏的处理 (Issue #6) |

非常感谢您的反馈！测试了修改前和修改后的代码情况如下:

这个问题我之前好像也遇到过，但是刚才尝试了几次都没有再次出现。可能是因为不同的操作系统和浏览器版本导致的差异，同时也可能与是否安装了其他微信读书脚本有关。

这是现在的代码可以达到的最窄的情况：

也试了你提供的代码，本地测试最窄如下：

然后普通情况如下：

总结下来，可能是现有的代码与你的配置不兼容，而提供的修改代码则在我的配置下也无法正常运行。

你可以 fork 这个仓库来保留你的配置，同时也能同步获取最新的更改
